nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/login':   # ajout spécifique pour login
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['POST', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            allow_credentials: true
            max_age: 3600

        '^/api/':   # garde le reste de ton API
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_credentials: true
            max_age: 3600
